### PR TITLE
Add tests for basic (API key) auth

### PR DESCRIPTION
**Pull request by nbarbettini**
Adds a few basic (no pun intended) API key auth tests.

### CODE REVIEW

**Comment by nbarbettini** [comment]
Pinging @edjiang for review :)

**Comment by edjiang** [comment]
Just curious, I don't see the success case tested?

**Comment by nbarbettini** [comment]
Good q @edjiang, the organization is a little wonky but we have the success case over here: https://github.com/stormpath/stormpath-framework-tck/blob/master/src/main/groovy/com/stormpath/tck/me/MeIT.groovy#L119

**Comment by edjiang** [comment]
Gotcha, I was confused how we forgot the Basic auth case. OK, let me try running this quickly then.

**Comment by edjiang** [comment]
Runs great!

**Comment by nbarbettini** [comment]
Thanks for reviewing @edjiang  😄

**Pull request merged**
