### PR TITLE
Login route tests

### LINKED ISSUE #45: Errors returned as JSON use API status and response
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/error-handling.md#error-handling-rules

### LINKED ISSUE #81: Serve a default HTML page with a login form for request type text/html
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/login.md#feature-description

### LINKED ISSUE #83: Serve the login view model for request type application/json
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/login.md#feature-description

### LINKED ISSUE #85: Only respond to GET and POST

### LINKED ISSUE #86: Default HTML form must require username and password
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/login.md#default-html-login-form

### LINKED ISSUE #88: Default HTML form should set OAuth 2.0 cookies on successful login
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/login.md#default-html-login-form

### LINKED ISSUE #89: Login view model should have a list of fields ordered by fieldOrder
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/login.md#login-view-model

### LINKED ISSUE #92: Login value can either be username or email
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/login.md#-post-body-format

### LINKED ISSUE #93: Login value can either be username or email when posting JSON
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/login.md#-post-body-format

### LINKED ISSUE #94: Omitting login or password will render the form with an error
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/login.md#-post-error-handling

### LINKED ISSUE #95: Omitting login or password when posting JSON results in an error
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/login.md#-post-error-handling

### LINKED ISSUE #97: Redirect to nextUri on successful authorization
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/login.md#-post-response-handling

### LINKED ISSUE #99: Redirect to URI specified by next query parameter on successful authorization
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/login.md#-post-response-handling

### LINKED ISSUE #100: Return account JSON on successful authorization for application/json
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/login.md#-post-response-handling

### LINKED ISSUE #101: Remove all linked resources from JSON account response
Related to #100 

Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/login.md#-post-response-handling

### LINKED ISSUE #102: Render unverified status message
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/login.md#-post-response-handling

> Your account verification email has been sent! Before you can log into your account, you need to activate your account by clicking the link we sent to your inbox. Didn't get the email? `<a href="#{stormpath.web.verifyEmail.uri}">Click Here</a>`

### LINKED ISSUE #103: Render verified status message
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/login.md#-post-response-handling

> Your Account Has Been Verified. You may now login.

### LINKED ISSUE #104: Render created status message
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/login.md#-post-response-handling

> Your Account Has Been Created. You may now login.

### LINKED ISSUE #105: Render forgot status message
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/login.md#-post-response-handling

> Password Reset Requested. If an account exists for the email provided, you will receive an email shortly.

### LINKED ISSUE #106: Render reset status message
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/login.md#-post-response-handling

> Password Reset Successfully. You can now login with your new password.

### LINKED ISSUE #107: Ignore bogus status query values
If `?status=` does not match one of the values here: https://github.com/stormpath/stormpath-framework-spec/blob/master/login.md#-post-response-handling

It should be ignored.

### LINKED ISSUE #108: Datetime fields in JSON account response should be serialized as ISO 8601

### LINKED ISSUE #109: Rerender form with error UX if login is unsuccessful
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/login.md#-post-error-handling

> For any errors, the response should be a 200 OK and the form should be re-rendered with a UX that indicates which field is in error and what can be done to fix the problem.

### LINKED ISSUE #110: Return JSON error from API if JSON login is unsuccessful
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/login.md#-post-error-handling

> Respond with the JSON error from the API, according to the Error Handling specification.

### LINKED ISSUE #114: HTML form should contain fields ordered by fieldOrder
As defined in web-config.yaml.

### LINKED ISSUE #168: JSON response should set OAuth 2.0 cookies on successful login

### LINKED ISSUE #177: Preserve value in login field on unsuccessful attempt

### PR DESCRIPTION
**Pull request by nbarbettini**
Fixes #45 
Fixes #83 
Fixes #85 
Fixes #89 
Fixes #93 
Fixes #95 
Fixes #81
Fixes #86
Fixes #88
Fixes #92 
Fixes #94
Fixes #97
Fixes #99
Fixes #100 
Fixes #101
Fixes #102
Fixes #103
Fixes #104
Fixes #105
Fixes #106
Fixes #107 
Fixes #108
Fixes #109
Fixes #110
Fixes #114 
Fixes #168 
Fixes #177

### CODE REVIEW

**Comment by nbarbettini** [comment]
Ready for review! :tada:

**Comment by nbarbettini** [comment]
No longer in progress: I've written tests for everything in the spec. Poke some holes in it!

**Comment by edjiang** [comment]
@nbarbettini, I'm happy with these and OK with pushing them live, if you're happy with my changes. By the way, this PR is for merging into `nate-oauth2`, so you might wanna fix that.

**Comment by nbarbettini** [comment]
@edjiang good catch, will fix. :+1:

**Comment by nbarbettini** [comment]
@edjiang I took more time to think about it and I don't agree with the removals. Here's why:
- If the framework is up to spec, it's just two more quick green tests. Not much overhead.
- On the other hand, in the unlikely weird edge case where these tests fail, we'd want to know about it.

Let's chat about it if you still feel differently.

**Pull request closed without merging**
