### PR TITLE
Requests should fall through

### PR DESCRIPTION
**Pull request by edjiang**
There’s no specific reason they should 404; they should be falling through so just not 200ing.

### CODE REVIEW

**Comment by nbarbettini** [comment]
(Disclaimer: This might be tricky since we have to support so many different environments and frameworks.)

I hear ya that it doesn't need to be 404 specifically. However, I think `not(200)` ignores the possibility of 5xx, which wouldn't be good. Maybe test for 4xx?

**Comment by edjiang** [comment]
If a request falls through, it could do anything. I could even see a framework 200 OKing, actually (which I think was the case in Laravel, in a discussion @bretterer had yesterday). We should test that it doesn't get the Stormpath response, and maybe that would look like testing that we don't get the login body.

**Comment by nbarbettini** [comment]
Yeah, maybe testing the body is the right way to go there. I'm not 100% sure. `statusCode < 500` to start?

**Comment by edjiang** [comment]
If it 500s, what's the fix? It seems like the 500 could be caused by the framework (on undefined fallthroughs), and would be a valid response IMO.

**Comment by nbarbettini** [comment]
My assumption was/is:
- 5xx -> something blew up in the integration logic
- 4xx -> client error

(That's our [error-handling](https://github.com/stormpath/stormpath-framework-spec/blob/master/error-handling.md#error-handling-rules) spec, at least)

But I didn't think about frameworks returning a 500 for an unhandled route. That's weird but possible I suppose. Do any of our frameworks do this currently?

**Comment by nbarbettini** [comment]
What do you want to do with this PR @edjiang?

Do you have any concerns re: going with something like `not(200) && not(500)`?

**Comment by edjiang** [comment]
KK

**Pull request merged**
