### PR TITLE
Dont check for deletion of a non existing access token cookie

### PR DESCRIPTION
**Pull request by DamirSvrtan**
Rails won't set the Set-Cookie header for cookie deletion if the cookie doesn't exist in the request:

The CookieIT#serverDeletesCookiesWhenRefreshingWithInvalidToken spec sends out only the refresh token cookie, not the access token, however expects to get headers for both back.

I believe this should be the correct assertion.

### CODE REVIEW

**Comment by edjiang** [comment]
Ah, I get why @dogeared was doing this modification, now: https://github.com/stormpath/stormpath-framework-tck/pull/266#discussion_r66310068

I think a better approach is to send an expired / invalid access token as well, to assert that both of them get deleted. Want to tackle that?

**Comment by DamirSvrtan** [comment]
I believe the best approach would be to leave the test as is with the modification that @dogeared made or the one that I made, and make an additional test with invalid access token and invalid refresh token.

How does that sound @edjiang ?

**Comment by edjiang** [comment]
Actually -- when I comented this morning, I thought that you said there was some Rails specific reason why this couldn't happen. For some reason, I must have misread. @nbarbettini and I decided to do it this way, because no matter what, we should just send the delete headers both cookies if the refresh token is invalid. Why not delete both in any case; is there a reason it needs to be conditional?

**Comment by DamirSvrtan** [comment]
You were right this morning when you read my comment - it is Rails Specific :)

If the request cookie doesn't exist, Rails won't send out at a 'Set-Cookie' header:

``` ruby
show-source cookies.delete
```

``` ruby
def delete(name, options = {})
  return unless @cookies.has_key? name.to_s
  ...
end
```

**Comment by edjiang** [comment]
Yeah, then I would make a test with two garbage tokens and let Rails delete both.

**Comment by DamirSvrtan** [comment]
@edjiang Added an invalid access token to the request.

**Comment by edjiang** [comment]
😎

**Pull request merged**
