### PR TITLE
Accept behavior tests

### LINKED ISSUE #72: Null or empty Accept header is treated as */*
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/requests.md#accept-header

### LINKED ISSUE #73: Accept: */* uses first value in web.produces as Content-Type
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/requests.md#accept-header

### LINKED ISSUE #75: Specifying valid Accept Content-Type returns that Content-Type
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/requests.md#accept-header

### LINKED ISSUE #76: Unknown Accept header is not handled
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/requests.md

If the request contains an `Accept` header that we don't recognize, pass on the request.

### PR DESCRIPTION
**Pull request by nbarbettini**
Fixes #72 
Fixes #73 
Fixes #75 
Fixes #76

### CODE REVIEW

**Comment by nbarbettini** [comment]
Interested if @lhazlewood or others think we should be testing for more complex `Accept` header string parsing. Right now it's only tossing softballs.

**Comment by lhazlewood** [comment]
I think this is a good enough start IMO.  I think we can add others if/when we find something that needs to be tested beyond the basics (e.g. to assert a particular use case that might affect a user).

**Comment by nbarbettini** [comment]
No longer in progress; these are ready for review.

**Comment by edjiang** [comment]
Behavior will be changed as per today's framework spec meeting. However, as I understand it we are only changing the behavior of the Accept header when the produces option only has one thing selected. So all of these tests are valid, as the default configuration produces both json and HTML.

However, we will need to test the new behavior once @robertjd codifies it in the Framework Spec.

**Pull request merged**
