### PR TITLE
Forgot Password tests

### LINKED ISSUE #140: Render form if the request type is text/html
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/password-reset.md#get-requests-with-accept-texthtml

### LINKED ISSUE #141: If query string contains invalid_sptoken, render message above form
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/password-reset.md#get-requests-with-accept-texthtml

### LINKED ISSUE #142: POST requests preferring application/json should respond with 200 OK
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/password-reset.md#post-requests

### LINKED ISSUE #143: POST requests preferring text/html should redirect to nextUri
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/password-reset.md#post-requests

### LINKED ISSUE #147: Redirect to errorUri for invalid sptoken on GET
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/password-reset.md#get-requests-with-accept-texthtml-1

### LINKED ISSUE #149: Render a form to collect new password for valid sptoken
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/password-reset.md#get-requests-with-accept-texthtml-1

### LINKED ISSUE #151: Redirect to forgotPassword.uri if sptoken is missing
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/password-reset.md#get-requests-with-accept-texthtml-1

### LINKED ISSUE #155: Return 200 OK and empty body for application/json POST
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/password-reset.md#post-handling

### LINKED ISSUE #158: Redirect to errorUri for invalid or expired token on POST
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/password-reset.md#post-handling

### LINKED ISSUE #159: Respond with API error for error during JSON POST
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/password-reset.md#post-handling

### LINKED ISSUE #165: Only GET and POST should be handled

### LINKED ISSUE #166: Only GET and POST should be handled

### LINKED ISSUE #215: GET should not be handled for JSON requests
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/password-reset.md#get-requests

### LINKED ISSUE #216: Return JSON error if sptoken is missing
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/password-reset.md#get-requests-1

``` javascript
{
    status: 400,
    message: 'sptoken parameter not provided.'
}
```

### LINKED ISSUE #239: Return JSON error if sptoken is invalid
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/password-reset.md#get-requests-1

### PR DESCRIPTION
**Pull request by nbarbettini**
The rest of the forgot/change password tests will require some additional trickery to capture the `sptoken` somehow. Haven't tackled that yet.

Fixes #165 
Fixes #215
Fixes #142 
Fixes #140 
Fixes #141 
Fixes #143
Fixes #166 
Fixes #147 
Fixes #151 
Fixes #239 
Fixes #216
Fixes #158 
Fixes #159
Fixes #149 
Fixes #155

### CODE REVIEW

**Comment by nbarbettini** [comment]
Ready for review! :+1:

**Comment by nbarbettini** [comment]
Now with Even More Tests :tada:

**Comment by edjiang** [comment]
@nbarbettini if these look good to you, please merge =]

**Comment by nbarbettini** [comment]
👍 !

**Pull request merged**
